matrix:
  include:
    - language: python
      python: 3.6
      script:
        - make
    - language: node_js
      node_js:
      - node
      cache:
        directories:
          - node_modules
      script: 
        - npm install -g serverless
        - sls deploy
notifications:
  email:
    - adambriandavis@gmail.com
